const articleData = [
  {
    articleID: 'art001',
    articleTitle: 'メロディの魔法',
    articleContent: '新しいメロディがどのようにして生まれるか...',
    songName: '夜空の星',
    artistName: '星野源',
    userID: '@melodymagic001',
    user: 'HarmonyFan',
    userAvatarUrl: 'https://api.dicebear.com/v2/avatars/melodymagic001.svg',
  },
  {
    articleID: 'art002',
    articleTitle: 'リズムの秘密',
    articleContent: 'リズムは音楽の骨格であり...',
    songName: '瞬き',
    artistName: 'back number',
    userID: '@rhythmsecret002',
    user: 'BeatMaster',
    userAvatarUrl: 'https://api.dicebear.com/v2/avatars/rhythmsecret002.svg',
  },
  {
    articleID: 'art003',
    articleTitle: 'ハーモニーの探求',
    articleContent: '和音の組み合わせが生み出すハーモニーについて...',
    songName: '打上花火',
    artistName: 'DAOKO × 米津玄師',
    userID: '@harmonysearch003',
    user: 'ChordExplorer',
    userAvatarUrl: 'https://api.dicebear.com/v2/avatars/harmonysearch003.svg',
  },
  {
    articleID: 'art004',
    articleTitle: 'ギターソロの魅力',
    articleContent: 'ギターソロが曲にどのような影響を与えるか...',
    songName: '紅蓮華',
    artistName: 'LiSA',
    userID: '@guitarsolo004',
    user: 'StringVirtuoso',
    userAvatarUrl: 'https://api.dicebear.com/v2/avatars/guitarsolo004.svg',
  },
  {
    articleID: 'art005',
    articleTitle: 'ジャズの即興演奏',
    articleContent: '即興演奏はジャズの魂であり...',
    songName: 'What a Wonderful World',
    artistName: 'Louis Armstrong',
    userID: '@jazzimprov005',
    user: 'JazzConnoisseur',
    userAvatarUrl: 'https://api.dicebear.com/v2/avatars/jazzimprov005.svg',
  },
  {
    articleID: 'art006',
    articleTitle: 'クラシック音楽の深遠',
    articleContent: 'クラシック音楽が現代音楽に与える影響について...',
    songName: 'ノクターン',
    artistName: 'ショパン',
    userID: '@classicaldepth006',
    user: 'OrchestraFan',
    userAvatarUrl: 'https://api.dicebear.com/v2/avatars/classicaldepth006.svg',
  },
  {
    articleID: 'art007',
    articleTitle: 'ポップミュージックの進化',
    articleContent: 'ポップミュージックが社会に与える影響とは...',
    songName: 'Lemon',
    artistName: '米津玄師',
    userID: '@popmusic007',
    user: 'PopCulture',
    userAvatarUrl: 'https://api.dicebear.com/v2/avatars/popmusic007.svg',
  },
  {
    articleID: 'art008',
    articleTitle: 'ロックの伝説',
    articleContent: 'ロック音楽の歴史とそのアイコンたち...',
    songName: 'Bohemian Rhapsody',
    artistName: 'Queen',
    userID: '@rocklegend008',
    user: 'RocknRoller',
    userAvatarUrl: 'https://api.dicebear.com/v2/avatars/rocklegend008.svg',
  },
  {
    articleID: 'art009',
    articleTitle: 'エレクトロニックミュージックの未来',
    articleContent: 'テクノロジーが生み出す新しい音の世界...',
    songName: 'Shelter',
    artistName: 'Porter Robinson & Madeon',
    userID: '@electronic009',
    user: 'SynthLover',
    userAvatarUrl: 'https://api.dicebear.com/v2/avatars/electronic009.svg',
  },
  {
    articleID: 'art010',
    articleTitle: '音楽プロデューサーの役割',
    articleContent: '音楽プロデューサーがアーティストと共に作り上げる作品...',
    songName: 'Fantasy',
    artistName: 'Mariah Carey',
    userID: '@musicproducer010',
    user: 'StudioWizard',
    userAvatarUrl: 'https://api.dicebear.com/v2/avatars/musicproducer010.svg',
  },
];

export default articleData;
