const articleData = [
  {
    articleID: 'art001',
    articleTitle: 'メロディの魔法',
    articleContent: '新しいメロディがどのようにして生まれるか...',
    songName: '喜劇',
    artistName: '星野源',
    artworkUrl:
      'https://www.jvcmusic.co.jp/img/jackets/VE3WA-19681.jpg?_c=da1f6d2bf43846614a60e7d4c8163155',
    userID: '@Taro1234',
    user: 'たろう',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'review',
  },
  {
    articleID: 'art002',
    articleTitle: 'リズムの秘密',
    articleContent: 'リズムは音楽の骨格であり...',
    songName: '瞬き',
    artistName: 'back number',
    artworkUrl:
      'https://m.media-amazon.com/images/I/91yRwjDaxML._UF1000,1000_QL80_.jpg',
    userID: '@rhythmsecret002',
    user: 'BeatMaster',
    userAvatarUrl: 'https://api.dicebear.com/8.x/lorelei/png',
    type: 'live report',
  },
  {
    articleID: 'art003',
    articleTitle: 'ハーモニーの探求',
    articleContent: '和音の組み合わせが生み出すハーモニーについて...',
    songName: '打上花火',
    artistName: 'DAOKO × 米津玄師',
    artworkUrl:
      'https://m.media-amazon.com/images/I/81WGI00wmrL._UF1000,1000_QL80_.jpg',
    userID: '@hNinjaX',
    user: '忍者X',
    userAvatarUrl: 'https://api.dicebear.com/8.x/bottts/png',
    type: 'general',
  },
  {
    articleID: 'art004',
    articleTitle: 'ギターソロの魅力',
    articleContent: 'ギターソロが曲にどのような影響を与えるか...',
    songName: '紅蓮華',
    artistName: 'LiSA',
    artworkUrl:
      'https://m.media-amazon.com/images/I/71GJUXIF6QL._UF1000,1000_QL80_.jpg',
    userID: '@Yumi789',
    user: 'ゆみちゃん',
    userAvatarUrl: 'https://api.dicebear.com/8.x/personas/png',
    type: 'playlist',
  },
  {
    articleID: 'art005',
    articleTitle: 'ジャズの即興演奏',
    articleContent: '即興演奏はジャズの魂であり...',
    songName: 'What a Wonderful World',
    artistName: 'Louis Armstrong',
    artworkUrl:
      'https://m.media-amazon.com/images/I/71oBdOk+2BL._UF1000,1000_QL80_.jpg',
    userID: '@TokyoGhoul',
    user: '東京喰種👹',
    userAvatarUrl: 'https://api.dicebear.com/8.x/notionists/png',
    type: 'review',
  },
  {
    articleID: 'art006',
    articleTitle: 'クラシック音楽の深遠',
    articleContent: 'クラシック音楽が現代音楽に与える影響について...',
    songName: 'ノクターン',
    artistName: 'ショパン',
    artworkUrl: 'https://cdn.goope.jp/83265/231001124206-6518ea8eec9c2.jpg',
    userID: '@Neko123',
    user: 'ねこまるにゃんこ',
    userAvatarUrl:
      'https://api.dicebear.com/8.x/avataaars/png?seed=Felix&accessories=round&eyebrows=raisedExcited&skinColor=ffdbb4&top=bob',
    type: 'live report',
  },
  {
    articleID: 'art007',
    articleTitle: 'ポップミュージックの進化',
    articleContent: 'ポップミュージックが社会に与える影響とは...',
    songName: 'Lemon',
    artistName: '米津玄師',
    artworkUrl:
      'https://m.media-amazon.com/images/I/91ufveUUmGL._UF1000,1000_QL80_.jpg',
    userID: '@MochiMochi',
    user: 'もちもち大福',
    userAvatarUrl: 'https://api.dicebear.com/8.x/croodles/png',
    type: 'general',
  },
  {
    articleID: 'art008',
    articleTitle: 'ロックの伝説',
    articleContent: 'ロック音楽の歴史とそのアイコンたち...',
    songName: 'Bohemian Rhapsody',
    artistName: 'Queen',
    artworkUrl:
      'https://m.media-amazon.com/images/I/61dk4SHy1CL._UF1000,1000_QL80_.jpg',
    userID: '@GamerPro9',
    user: 'ゲーマー進化論',
    userAvatarUrl: 'https://api.dicebear.com/8.x/big-ears/png',
    type: 'playlist',
  },
  {
    articleID: 'art009',
    articleTitle: 'エレクトロニックミュージックの未来',
    articleContent: 'テクノロジーが生み出す新しい音の世界...',
    songName: 'Shelter',
    artistName: 'Porter Robinson & Madeon',
    artworkUrl:
      'https://m.media-amazon.com/images/I/61SywDA813L._UF1000,1000_QL80_.jpg',
    userID: '@RamenKing88',
    user: 'ラーメン王',
    userAvatarUrl: 'https://api.dicebear.com/8.x/micah/png',
    type: 'review',
  },
  {
    articleID: 'art010',
    articleTitle: '音楽プロデューサーの役割',
    articleContent: '音楽プロデューサーがアーティストと共に作り上げる作品...',
    songName: 'Fantasy',
    artistName: 'Mariah Carey',
    userID: '@KawaiiQueen',
    artworkUrl:
      'https://m.media-amazon.com/images/I/61rGJYmZZbL._UF1000,1000_QL80_.jpg',
    user: 'かわいい女王様',
    userAvatarUrl: 'https://api.dicebear.com/8.x/thumbs/png',
    type: 'live report',
  },
];

export default articleData;
