const postData = [
  {
    postID: 1,
    postContent: '今日もいい日だ！',
    ImageUrl: [],
    userID: '@Taro1234',
    user: 'たろう',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    createdAt: '2024-07-12T14:20:34Z',
    likes: 135,
  },
  {
    postID: 2,
    postContent: '待って！ぶーやん最高すぎるだろ！',
    ImageUrl: [],
    userID: '@rhythmsecret002',
    user: 'BeatMaster',
    userAvatarUrl: 'https://api.dicebear.com/8.x/lorelei/png',
    createdAt: '2024-06-20T11:45:12Z',
    likes: 278,
  },
  {
    postID: 3,
    postContent:
      'taka...どうしてそんなに歌が上手いんだ。俺も歌えるようになりたい。',
    ImageUrl: [
      'https://imgs.ototoy.jp/imgs/jacket/1083/00050800.1638931680.7485_320.jpg',
      'https://assets.st-note.com/production/uploads/images/118769644/rectangle_large_type_2_dfac95fd8fb3ca429c798b9656b2c54d.png?width=2000&height=2000&fit=bounds&format=jpg&quality=85',
    ],
    userID: '@hNinjaX',
    user: '忍者X',
    userAvatarUrl: 'https://api.dicebear.com/8.x/bottts/png',
    createdAt: '2024-05-15T09:30:27Z',
    likes: 520,
  },
  {
    postID: 4,
    postContent: '今年はラブシャが熱いのかもしれない。夏フェス最高',
    ImageUrl: [],
    userID: '@Yumi789',
    user: 'ゆみちゃん',
    userAvatarUrl: 'https://api.dicebear.com/8.x/personas/png',
    createdAt: '2024-07-01T18:15:44Z',
    likes: 420,
  },
  {
    postID: 5,
    postContent: '新しいarticle投稿しました！',
    ImageUrl: [],
    userID: '@TokyoGhoul',
    user: '東京喰種👹',
    userAvatarUrl: 'https://api.dicebear.com/8.x/notionists/png',
    createdAt: '2024-06-25T20:10:59Z',
    likes: 345,
  },
  {
    postID: 6,
    postContent: 'ライブハウスが彼女との出会いです！',
    ImageUrl: [],
    userID: '@Neko123',
    user: 'ねこまるにゃんこ',
    userAvatarUrl:
      'https://api.dicebear.com/8.x/avataaars/png?seed=Felix&accessories=round&eyebrows=raisedExcited&skinColor=ffdbb4&top=bob',
    createdAt: '2024-07-05T13:40:18Z',
    likes: 250,
  },
  {
    postID: 7,
    postContent: 'a to b',
    ImageUrl: [
      'https://m.media-amazon.com/images/I/91ufveUUmGL._UF1000,1000_QL80_.jpg',
      'https://assets.st-note.com/production/uploads/images/119567308/rectangle_large_type_2_64867acd466f0affc7c9fa6020ecd244.png?width=2000&height=2000&fit=bounds&format=jpg&quality=85',
      'https://m.media-amazon.com/images/I/71GJUXIF6QL._UF1000,1000_QL80_.jpg',
    ],
    userID: '@MochiMochi',
    user: 'もちもち大福',
    userAvatarUrl: 'https://api.dicebear.com/8.x/croodles/png',
    createdAt: '2024-06-30T08:55:13Z',
    likes: 180,
  },
  {
    postID: 8,
    postContent: '今日の朝ごはんは最高だった！',
    ImageUrl: [],
    userID: '@MorningFan',
    user: '朝ごはん好き',
    userAvatarUrl: 'https://api.dicebear.com/8.x/adventurer/png',
    createdAt: '2024-07-10T07:15:30Z',
    likes: 210,
  },
  {
    postID: 9,
    postContent: 'この映画は必見だ！',
    ImageUrl: [],
    userID: '@MovieBuff',
    user: '映画マニア',
    userAvatarUrl: 'https://api.dicebear.com/8.x/identicon/png',
    createdAt: '2024-06-15T21:30:45Z',
    likes: 395,
  },
  {
    postID: 10,
    postContent: '週末のキャンプが楽しみ！',
    ImageUrl: [],
    userID: '@Camper123',
    user: 'キャンプ好き',
    userAvatarUrl: 'https://api.dicebear.com/8.x/bottts/png',
    createdAt: '2024-07-03T16:22:11Z',
    likes: 480,
  },
  {
    postID: 11,
    postContent: '新しいレシピを試してみたよ！',
    ImageUrl: [
      'https://api.dicebear.com/8.x/micah/png',
      'https://api.dicebear.com/8.x/micah/png',
      'https://api.dicebear.com/8.x/micah/png',
      'https://api.dicebear.com/8.x/micah/png',
    ],
    userID: '@ChefMaster',
    user: 'シェフマスター',
    userAvatarUrl: 'https://api.dicebear.com/8.x/micah/png',
    createdAt: '2024-06-28T11:05:20Z',
    likes: 320,
  },
];

export default postData;
