const postData = [
  {
    postID: 'post001',
    postContent: '今日もいい日だ！',
    songName: '',
    artistName: '',
    musicUrl: '',
    ImageUrl: '',
    userID: '@Taro1234',
    user: 'たろう',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
  },
  {
    postID: 'post002',
    postContent: '待って！ぶーやん最高すぎるだろ！',
    songName: '',
    artistName: '',
    musicUrl: '',
    ImageUrl: '',
    userID: '@rhythmsecret002',
    user: 'BeatMaster',
    userAvatarUrl: 'https://api.dicebear.com/8.x/lorelei/png',
  },
  {
    postID: 'post003',
    postContent: 'taka...どうしてそんなに歌が上手いんだ。俺も歌えるようになりたい。',
    songName: '',
    artistName: '',
    musicUrl: '',
    ImageUrl: '',
    userID: '@hNinjaX',
    user: '忍者X',
    userAvatarUrl: 'https://api.dicebear.com/8.x/bottts/png',
  },
  {
    postID: 'post004',
    postContent: '今年はラブシャが熱いのかもしれない。夏フェス最高',
    songName: '',
    artistName: '',
    musicUrl: '',
    ImageUrl: '',
    userID: '@Yumi789',
    user: 'ゆみちゃん',
    userAvatarUrl: 'https://api.dicebear.com/8.x/personas/png',
  },
  {
    postID: 'post005',
    postContent: '新しいarticle投稿しました！',
    songName: 'What a Wonderful World',
    artistName: 'Louis Armstrong',
    musicUrl: 'https://m.media-amazon.com/images/I/71oBdOk+2BL._UF1000,1000_QL80_.jpg',
    ImageUrl: '',
    userID: '@TokyoGhoul',
    user: '東京喰種👹',
    userAvatarUrl: 'https://api.dicebear.com/8.x/notionists/png',
  },
  {
    postID: 'post006',
    postContent: 'ライブハウスが彼女との出会いです！',
    songName: '',
    artistName: '',
    musicUrl: '',
    ImageUrl: '',
    userID: '@Neko123',
    user: 'ねこまるにゃんこ',
    userAvatarUrl:
      'https://api.dicebear.com/8.x/avataaars/png?seed=Felix&accessories=round&eyebrows=raisedExcited&skinColor=ffdbb4&top=bob',
    
  },
  {
    postID: 'post007',
    postContent: 'a to b',
    songName: '',
    artistName: '',
    musicUrl: '',
    ImageUrl: 'https://api.dicebear.com/8.x/croodles/png',
    userID: '@MochiMochi',
    user: 'もちもち大福',
    userAvatarUrl: 'https://api.dicebear.com/8.x/croodles/png',
  },
  
]

export default postData;
