const todaySongData = [
  {
    userID: '@Taro1234',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    songName: '視界の隅 朽ちる音',
    artistName: '(新川崎(仮))',
    artworkUrl:
      'https://content-jp.umgi.net/products/um/UMCK-5754_duI_extralarge.jpg?03052024121250',
    body: '今期の覇権、もしかすると今年の覇権を確定させるかのような一曲。この年でこのクオリティは普通のバンドでも中々ないでしょ......。早くライブで”宣戦布告”と”約束”の小指を掲げたい！',
    todaySongID: 1,
  },
  {
    userID: '@Taro1234',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    songName: 'じゃあな',
    artistName: 'ReoNa',
    artworkUrl:
      'https://pimg.awa.io/v2/jacket/beb025b544fee0db2700.w630.h630.v1718149492.jpg',
    body: 'あの捨て台詞「じゃあな」がこんなかっこいい曲になるとは、、、。やっぱりLIVE LAB.はアーティストRoNaの物語の文脈を取り込むのが異常にうまいよね！「そんなわけないじゃん「また明日」が怖いのに」と書けるのがReoNaの強さだよねー',
    todaySongID: 2,
  },
  {
    userID: '@rhythmsecret002',
    userAvatarUrl: 'https://api.dicebear.com/8.x/lorelei/png',
    songName: 'ベーコンエピ',
    artistName: 'TOMOO',
    body: '「そして繋いだ右手が笑えるほどぱずるみたいだったこと」恋人繋ぎのことだと思っているけど、パズルみたいにそんなぴったりはまることなんて本当に奇跡すぎてどう生きたらこんな歌詞浮かぶのか教えてほしい。友達が「恋愛経験少ない人ホイホイ」って言ってたのはめっちゃウケた笑',
    todaySongID: 3,
  },
  {
    userID: '@hNinjaX',
    userAvatarUrl: 'https://api.dicebear.com/8.x/bottts/png',
    songName: 'Beyond the Gray Skay',
    artistName: '百華',
    body: 'ピアノベースの入り、サビ前のブレイクとコーラスの使いかた、サビのメロディ展開が平成後期～末期の”あの頃”のアニソンのそれで懐古厨になってしまった。。。',
    todaySongID: 4,
  },
  {
    userID: '@Yumi789',
    userAvatarUrl: 'https://api.dicebear.com/8.x/personas/png',
    songName: 'Tap Tap Dance',
    artistName: '緑黄色社会',
    body: 'リズム隊の超メリハリの利いたビートがおしゃれすぎる！夜祭での演奏もやばかった‼',
    todaySongID: 5,
  },
  {
    userID: '@TokyoGhoul',
    userAvatarUrl: 'https://api.dicebear.com/8.x/notionists/png',
    songName: '忘れないように',
    artistName: 'イクラノドン',
    body: '祝円盤！やっと聴ける！Deepとどっちにするか迷ったけど彼女たちの意思を尊重して。脱退はめっちゃ悲しいけどこれからもイクラノドンの音楽がいつまでも聴けますように。よろしくどーぞ！',
    todaySongID: 6,
  },
  {
    userID: '@Neko123',
    userAvatarUrl:
      'https://api.dicebear.com/8.x/avataaars/png?seed=Felix&accessories=round&eyebrows=raisedExcited&skinColor=ffdbb4&top=bob',
    songName: '27',
    artistName: 'SUPER BEAVER',
    body: '27歳になりました。僕にとってのロックスターはまだ生きてます。生き続けるしかないなー、',
    todaySongID: 7,
  },
  {
    userID: '@MochiMochi',
    userAvatarUrl: 'https://api.dicebear.com/8.x/croodles/png',
    songName: 'Fire Cracker',
    artistName: 'ELLEGARDEN',
    body: 'いったんきいてほしいです。パンクの要素ありつつ、メロディを立たせて切なさも出せる。個人的にはこういうのがエモだと思ってる。エモいじゃない、エモ。',
    todaySongID: 8,
  },
  {
    userID: '@GamerPro9',
    userAvatarUrl: 'https://api.dicebear.com/8.x/big-ears/png',
    songName: '嘘月',
    artistName: 'ヨルシカ',
    body: 'この曲は、言語化できないけど好きなんです。なんか、もっとシンプルだった時の自分を思い出します、、',
    todaySongID: 9,
  },
  {
    userID: 'ラーメン王',
    userAvatarUrl: 'https://api.dicebear.com/8.x/micah/png',
    songName: 'We are',
    artistName: 'ONE OK ROCK',
    body: 'アーティストとか、曲のために生きるんじゃなくて、自分の糧にしなきゃなと思った。takaのmcに心から納得できた。',
    todaySongID: 10,
  },
  {
    userID: 'かわいい女王様',
    userAvatarUrl: 'https://api.dicebear.com/8.x/thumbs/png',
    songName: 'One More Right',
    artistName: 'LINKIN PARK',
    body: 'どれだけ好きでも、他人であることには変わりなくて、好きなものの変化を許容できずに、攻撃してしまうってのは、一方的に、それを内包化した錯覚に陥って依存してるだけなんだろーなー。',
    todaySongID: 11,
  },
];

export default todaySongData;
