const userArticleData = [
  {
    articleID: 'art002',
    articleTitle: 'ライブの興奮を再び',
    articleBody: '昨夜のライブは本当に素晴らしかった！',
    songName: '打上花火',
    artistName: 'DAOKO × 米津玄師',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'liveReport',
  },
  {
    articleID: 'art003',
    articleTitle: '日常を彩るプレイリスト',
    articleBody: 'このプレイリストで一日をスタートしよう！',
    songName: 'シュガーソングとビターステップ',
    artistName: 'UNISON SQUARE GARDEN',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'playList',
  },
  {
    articleID: 'art004',
    articleTitle: '新アルバムの感想',
    articleBody: '新しいアルバムは期待を裏切らない出来栄えだ。',
    songName: '香水',
    artistName: '瑛人',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'review',
  },
  {
    articleID: 'art005',
    articleTitle: '音楽の力',
    articleBody: '音楽は人生の最高のパートナーだ。',
    songName: 'Lemon',
    artistName: '米津玄師',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'general',
  },
  {
    articleID: 'art006',
    articleTitle: 'コンサート体験記',
    articleBody: 'ステージからのエネルギーが伝わってきた。',
    songName: 'Pretender',
    artistName: 'Official髭男dism',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'liveReport',
  },
  {
    articleID: 'art007',
    articleTitle: 'おすすめのバンド',
    articleBody: 'このバンドのサウンドは他とは一線を画す。',
    songName: 'インフェルノ',
    artistName: 'Mrs. GREEN APPLE',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'general',
  },
  {
    articleID: 'art008',
    articleTitle: '究極のリラックスソング',
    articleBody: 'この曲でリラックスタイムを。',
    songName: '炎',
    artistName: 'LiSA',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'playList',
  },
  {
    articleID: 'art009',
    articleTitle: '新曲レビュー',
    articleBody: '新曲は彼らの新たな一面を見せてくれた。',
    songName: '夜に駆ける',
    artistName: 'YOASOBI',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'review',
  },
  {
    articleID: 'art010',
    articleTitle: '音楽とともに',
    articleBody: '毎日音楽とともに過ごすことで、心が豊かになる。',
    songName: 'マリーゴールド',
    artistName: 'あいみょん',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'general',
  },
  {
    articleID: 'art011',
    articleTitle: '今週のおすすめ曲',
    articleBody: 'この曲を聴いて、新しい一週間を始めよう！',
    songName: '紅蓮華',
    artistName: 'LiSA',
    userAvatarUrl: 'https://api.dicebear.com/8.x/pixel-art/png',
    type: 'playList',
  },
];
