
name: Go Test

on:
  push:
    paths: "ut/fizzbuzz.go"
    paths: "ut/fizzbuzz_test.go"
  pull_requests:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.16'

    - name: Test
      run: go test -v "./ut" 